version: "3.7"
services:
  v2ray:
    image: v2fly/v2fly-core:v4.45.2
    container_name: v2ray
    expose:
      - 10000
    command: v2ray --config=/etc/v2ray/config.json
    volumes:
      - ${PWD}/v2ray-server.json:/etc/v2ray/config.json
    restart: unless-stopped

